alias vu='vagrant up'
alias vh='vagrant halt'
alias vd='vagrant destroy'
alias vpr='vagrant global-status --prune'
alias vbl='vagrant box list'
alias vidb75='vagrant init debian75-x64-11'
alias vidb8='vagrant init debian81x64-00'